version: '3.7'

services:
  backend:
    container_name: "iban-checker_backend"
    image: iban-checked-backend:latest
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    links:
      - "postgres_backend:db"
    depends_on:
      - postgres_backend
    volumes:
      - ./:/app
    networks:
      - iban_checker

  postgres_backend:
    image: postgres:13.7-alpine3.16
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes:
      - postgres_backend:/var/lib/postgresql_backend/data
    networks:
      - iban_checker

volumes:
  postgres_backend:

networks:
  iban_checker:
    name: 'iban-checker-network'
